package com.aerosuite.crs;

import java.util.Locale;

public final class OsCrsLabels {

    private final String title;
    private final String certificado;
    private final String os;
    private final String cliente;
    private final String pn;
    private final String sn;
    private final String matricula;
    private final String tipoServico;
    private final String emitidoEm;
    private final String liberadoPor;
    private final String cargo;
    private final String observacoes;
    private final String checklistTitle;
    private final String footer;

    private OsCrsLabels(
            String title,
            String certificado,
            String os,
            String cliente,
            String pn,
            String sn,
            String matricula,
            String tipoServico,
            String emitidoEm,
            String liberadoPor,
            String cargo,
            String observacoes,
            String checklistTitle,
            String footer) {
        this.title = title;
        this.certificado = certificado;
        this.os = os;
        this.cliente = cliente;
        this.pn = pn;
        this.sn = sn;
        this.matricula = matricula;
        this.tipoServico = tipoServico;
        this.emitidoEm = emitidoEm;
        this.liberadoPor = liberadoPor;
        this.cargo = cargo;
        this.observacoes = observacoes;
        this.checklistTitle = checklistTitle;
        this.footer = footer;
    }

    public static OsCrsLabels forLocale(String locale) {
        String key = locale != null ? locale.toLowerCase(Locale.ROOT) : "pt-br";
        if (key.startsWith("en")) {
            return en();
        }
        if (key.startsWith("es")) {
            return es();
        }
        if (key.startsWith("fr")) {
            return fr();
        }
        return pt();
    }

    public String title() {
        return title;
    }

    public String certificado() {
        return certificado;
    }

    public String os() {
        return os;
    }

    public String cliente() {
        return cliente;
    }

    public String pn() {
        return pn;
    }

    public String sn() {
        return sn;
    }

    public String matricula() {
        return matricula;
    }

    public String tipoServico() {
        return tipoServico;
    }

    public String emitidoEm() {
        return emitidoEm;
    }

    public String liberadoPor() {
        return liberadoPor;
    }

    public String cargo() {
        return cargo;
    }

    public String observacoes() {
        return observacoes;
    }

    public String checklistTitle() {
        return checklistTitle;
    }

    public String footer() {
        return footer;
    }

    private static OsCrsLabels pt() {
        return new OsCrsLabels(
                "Certificado de liberação para serviço (CRS)",
                "Nº certificado",
                "Ordem de serviço",
                "Cliente",
                "Part Number",
                "Serial Number",
                "Marcas / matrícula",
                "Tipo de serviço",
                "Emitido em",
                "Liberado por",
                "Função / habilitação",
                "Observações / ressalvas",
                "Checklist de liberação",
                "Documento gerado pela Aero Suite. A validade regulatória depende do manual de manutenção "
                        + "e da aprovação da organização (Part 145 / RBAC 145).");
    }

    private static OsCrsLabels en() {
        return new OsCrsLabels(
                "Certificate of release to service (CRS)",
                "Certificate no.",
                "Work order",
                "Customer",
                "Part Number",
                "Serial Number",
                "Registration",
                "Service type",
                "Issued at",
                "Released by",
                "Role / authorization",
                "Remarks / limitations",
                "Release checklist",
                "Document generated by Aero Suite. Regulatory validity depends on the maintenance manual "
                        + "and organization approval (Part 145).");
    }

    private static OsCrsLabels es() {
        return new OsCrsLabels(
                "Certificado de liberación para servicio (CRS)",
                "Nº certificado",
                "Orden de servicio",
                "Cliente",
                "Part Number",
                "Serial Number",
                "Matrícula",
                "Tipo de servicio",
                "Emitido el",
                "Liberado por",
                "Función / habilitación",
                "Observaciones / reservas",
                "Lista de liberación",
                "Documento generado por Aero Suite. La validez regulatoria depende del manual de mantenimiento "
                        + "y la aprobación de la organización (Part 145).");
    }

    private static OsCrsLabels fr() {
        return new OsCrsLabels(
                "Certificat de remise en service (CRS)",
                "Nº certificat",
                "Ordre de service",
                "Client",
                "Part Number",
                "Serial Number",
                "Immatriculation",
                "Type de service",
                "Émis le",
                "Libéré par",
                "Fonction / habilitation",
                "Observations / réserves",
                "Liste de libération",
                "Document généré par Aero Suite. La validité réglementaire dépend du manuel de maintenance "
                        + "et de l'agrément de l'organisation (Part 145).");
    }
}
