fingerprint
lt-cred-mech
no-multicast-peers
no-cli
no-tlsv1
no-tlsv1_1
stale-nonce=600
realm=aerosupport.example.com
user=aerosupport:CHANGE_THIS_LONG_RANDOM_PASSWORD
min-port=49160
max-port=49200
log-file=stdout
simple-log

