apiVersion: v1
kind: Service
metadata:
  name: {{ include "aerosuite.fullname" . }}-web
  labels:
    {{- include "aerosuite.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "aerosuite.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
